# Dockerfile for React client

# get the base node image
FROM node:10.16-alpine

# set the working dir for container
WORKDIR /frontend

# copy the json file first
COPY package*.json ./

# install npm dependencies

RUN npm install --silent

# copy other project files
COPY . .

EXPOSE 3000

# build the folder
CMD ["npm","start"]